# Generated by Django 2.2rc1 on 2019-09-17 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_song_is_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='album_logo',
            field=models.FileField(default=True, max_length=500, upload_to='music/'),
            preserve_default=False,
        ),
    ]
